server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0




#    lettuce:
#        pool:
#          max-active: 10
#          max-idle: 10
#          min-idle: 1
#          time-between-eviction-runs: 3000s
#    timeout: 3000s
#  jackson:
#    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包

logging:
  level:
    com.hmdp: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true



